# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            src/**/*.*
            .storybook/**/*.*
            !src/**/__*__

        # Caches
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v2
        if: env.GIT_DIFF
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline
        if: env.GIT_DIFF
