name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prebuild:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      # Setup environment
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          check-latest: true

      # Install
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      # Typecheck
      - name: Cache tsc
        uses: actions/cache@v2
        with:
          path: ./tsconfig.tsbuildinfo
          key: ${{ runner.os }}-cache-tsc

      - name: Typecheck
        run: npm run typecheck

      # Test
      - name: Test
        run: npm run test

      # Lint
      - name: Cache eslint
        uses: actions/cache@v2
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-cache-eslint

      - name: Cache stylelint
        uses: actions/cache@v2
        with:
          path: ./.stylelintcache
          key: ${{ runner.os }}-cache-stylelint

      - name: Lint
        run: npm run lint

      # Commit
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}

      - name: Build Storybook
        run: npm run build:storybook

        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
          # autoAcceptChanges: true # 👈 Option to accept all changes
          exitOnceUploaded: true
          skip: '@(renovate/**|dependabot/**)'